export default [
    // static, general
    {shortName: 1, obisCode: '1.4.0', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), current avg. 1'},
    {shortName: 2, obisCode: '1.5.0', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), average'},
    {shortName: 3, obisCode: '1.6.0', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), maximum, total'},
    {shortName: 4, obisCode: '1.6.1', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), maximum, tariff T1'},
    {shortName: 5, obisCode: '1.6.2', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), maximum, tariff T2'},
    {shortName: 6, obisCode: '1.6.3', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), maximum, tariff T3'},
    {shortName: 7, obisCode: '1.6.4', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), maximum, tariff T4'},
    {shortName: 8, obisCode: '1.8.0', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), total'},
    {shortName: 9, obisCode: '1.8.1', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), tariff T1'},
    {shortName: 10, obisCode: '1.8.2', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), tariff T2'},
    {shortName: 11, obisCode: '1.8.3', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), tariff T3'},
    {shortName: 12, obisCode: '1.8.4', isStatic: true, isGeneral: true, description: 'active power+ (QI+QIV), tariff T4'},
    {shortName: 13, obisCode: '2.4.0', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), current avg. 1'},
    {shortName: 14, obisCode: '2.5.0', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), average'},
    {shortName: 15, obisCode: '2.6.0', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), maximum, total'},
    {shortName: 16, obisCode: '2.6.1', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), maximum, tariff T1'},
    {shortName: 17, obisCode: '2.6.2', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), maximum, tariff T2'},
    {shortName: 18, obisCode: '2.6.3', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), maximum, tariff T3'},
    {shortName: 19, obisCode: '2.6.4', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), maximum, tariff T4'},
    {shortName: 20, obisCode: '2.8.0', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), total'},
    {shortName: 21, obisCode: '2.8.1', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), tariff T1'},
    {shortName: 22, obisCode: '2.8.2', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), tariff T2'},
    {shortName: 23, obisCode: '2.8.3', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), tariff T3'},
    {shortName: 24, obisCode: '2.8.4', isStatic: true, isGeneral: true, description: 'active power- (QII+QIII), tariff T4'},
    {shortName: 25, obisCode: '3.4.0', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), current avg. 1'},
    {shortName: 26, obisCode: '3.5.0', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), average'},
    {shortName: 27, obisCode: '3.6.0', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), maximum, total'},
    {shortName: 28, obisCode: '3.6.1', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), maximum, tariff T1'},
    {shortName: 39, obisCode: '3.6.2', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), maximum, tariff T2'},
    {shortName: 30, obisCode: '3.6.3', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), maximum, tariff T3'},
    {shortName: 31, obisCode: '3.6.4', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), maximum, tariff T4'},
    {shortName: 32, obisCode: '3.8.0', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), total'},
    {shortName: 33, obisCode: '3.8.1', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), tariff T1'},
    {shortName: 34, obisCode: '3.8.2', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), tariff T2'},
    {shortName: 35, obisCode: '3.8.3', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), tariff T3'},
    {shortName: 36, obisCode: '3.8.4', isStatic: true, isGeneral: true, description: 'reactive power+ (QI+QII), tariff T4'},
    {shortName: 37, obisCode: '4.4.0', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), current avg. 1'},
    {shortName: 38, obisCode: '4.5.0', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), average'},
    {shortName: 39, obisCode: '4.6.0', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), maximum, total'},
    {shortName: 40, obisCode: '4.6.1', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), maximum, tariff T1'},
    {shortName: 41, obisCode: '4.6.2', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), maximum, tariff T2'},
    {shortName: 42, obisCode: '4.6.3', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), maximum, tariff T3'},
    {shortName: 43, obisCode: '4.6.4', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), maximum, tariff T4'},
    {shortName: 44, obisCode: '4.8.0', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), total'},
    {shortName: 45, obisCode: '4.8.1', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), tariff T1'},
    {shortName: 46, obisCode: '4.8.2', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), tariff T2'},
    {shortName: 47, obisCode: '4.8.3', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), tariff T3'},
    {shortName: 48, obisCode: '4.8.4', isStatic: true, isGeneral: true, description: 'reactive power- (QIII+QIV), tariff T4'},
    {shortName: 49, obisCode: '5.4.0', isStatic: true, isGeneral: true, description: 'reactive power QI, current avg. 1'},
    {shortName: 50, obisCode: '5.5.0', isStatic: true, isGeneral: true, description: 'reactive power QI, average'},
    {shortName: 51, obisCode: '5.6.0', isStatic: true, isGeneral: true, description: 'reactive power QI, maximum, total'},
    {shortName: 52, obisCode: '5.6.1', isStatic: true, isGeneral: true, description: 'reactive power QI, maximum, tariff T1'},
    {shortName: 53, obisCode: '5.6.2', isStatic: true, isGeneral: true, description: 'reactive power QI, maximum, tariff T2'},
    {shortName: 54, obisCode: '5.6.3', isStatic: true, isGeneral: true, description: 'reactive power QI, maximum, tariff T3'},
    {shortName: 55, obisCode: '5.6.4', isStatic: true, isGeneral: true, description: 'reactive power QI, maximum, tariff T4'},
    {shortName: 56, obisCode: '5.8.0', isStatic: true, isGeneral: true, description: 'reactive power QI, total'},
    {shortName: 57, obisCode: '5.8.1', isStatic: true, isGeneral: true, description: 'reactive power QI, tariff T1'},
    {shortName: 58, obisCode: '5.8.2', isStatic: true, isGeneral: true, description: 'reactive power QI, tariff T2'},
    {shortName: 59, obisCode: '5.8.3', isStatic: true, isGeneral: true, description: 'reactive power QI, tariff T3'},
    {shortName: 60, obisCode: '5.8.4', isStatic: true, isGeneral: true, description: 'reactive power QI, tariff T4'},
    {shortName: 61, obisCode: '6.4.0', isStatic: true, isGeneral: true, description: 'reactive power QII, current avg. 1'},
    {shortName: 62, obisCode: '6.5.0', isStatic: true, isGeneral: true, description: 'reactive power QII, average'},
    {shortName: 63, obisCode: '6.6.0', isStatic: true, isGeneral: true, description: 'reactive power QII, maximum, total'},
    {shortName: 64, obisCode: '6.6.1', isStatic: true, isGeneral: true, description: 'reactive power QII, maximum, tariff T1'},
    {shortName: 65, obisCode: '6.6.2', isStatic: true, isGeneral: true, description: 'reactive power QII, maximum, tariff T2'},
    {shortName: 66, obisCode: '6.6.3', isStatic: true, isGeneral: true, description: 'reactive power QII, maximum, tariff T3'},
    {shortName: 67, obisCode: '6.6.4', isStatic: true, isGeneral: true, description: 'reactive power QII, maximum, tariff T4'},
    {shortName: 68, obisCode: '6.8.0', isStatic: true, isGeneral: true, description: 'reactive power QII, total'},
    {shortName: 69, obisCode: '6.8.1', isStatic: true, isGeneral: true, description: 'reactive power QII, tariff T1'},
    {shortName: 70, obisCode: '6.8.2', isStatic: true, isGeneral: true, description: 'reactive power QII, tariff T2'},
    {shortName: 71, obisCode: '6.8.3', isStatic: true, isGeneral: true, description: 'reactive power QII, tariff T3'},
    {shortName: 72, obisCode: '6.8.4', isStatic: true, isGeneral: true, description: 'reactive power QII, tariff T4'},
    {shortName: 73, obisCode: '7.4.0', isStatic: true, isGeneral: true, description: 'reactive power QIII, current avg. 1'},
    {shortName: 74, obisCode: '7.5.0', isStatic: true, isGeneral: true, description: 'reactive power QIII, average'},
    {shortName: 75, obisCode: '7.6.0', isStatic: true, isGeneral: true, description: 'reactive power QIII, maximum, total'},
    {shortName: 76, obisCode: '7.6.1', isStatic: true, isGeneral: true, description: 'reactive power QIII, maximum, tariff T1'},
    {shortName: 77, obisCode: '7.6.2', isStatic: true, isGeneral: true, description: 'reactive power QIII, maximum, tariff T2'},
    {shortName: 78, obisCode: '7.6.3', isStatic: true, isGeneral: true, description: 'reactive power QIII, maximum, tariff T3'},
    {shortName: 79, obisCode: '7.6.4', isStatic: true, isGeneral: true, description: 'reactive power QIII, maximum, tariff T4'},
    {shortName: 80, obisCode: '7.8.0', isStatic: true, isGeneral: true, description: 'reactive power QIII, total'},
    {shortName: 81, obisCode: '7.8.1', isStatic: true, isGeneral: true, description: 'reactive power QIII, tariff T1'},
    {shortName: 82, obisCode: '7.8.2', isStatic: true, isGeneral: true, description: 'reactive power QIII, tariff T2'},
    {shortName: 83, obisCode: '7.8.3', isStatic: true, isGeneral: true, description: 'reactive power QIII, tariff T3'},
    {shortName: 84, obisCode: '7.8.4', isStatic: true, isGeneral: true, description: 'reactive power QIII, tariff T4'},
    {shortName: 85, obisCode: '8.4.0', isStatic: true, isGeneral: true, description: 'reactive power QIV, current avg. 1'},
    {shortName: 86, obisCode: '8.5.0', isStatic: true, isGeneral: true, description: 'reactive power QIV, average'},
    {shortName: 87, obisCode: '8.6.0', isStatic: true, isGeneral: true, description: 'reactive power QIV, maximum, total'},
    {shortName: 88, obisCode: '8.6.1', isStatic: true, isGeneral: true, description: 'reactive power QIV, maximum, tariff T1'},
    {shortName: 89, obisCode: '8.6.2', isStatic: true, isGeneral: true, description: 'reactive power QIV, maximum, tariff T2'},
    {shortName: 90, obisCode: '8.6.3', isStatic: true, isGeneral: true, description: 'reactive power QIV, maximum, tariff T3'},
    {shortName: 91, obisCode: '8.6.4', isStatic: true, isGeneral: true, description: 'reactive power QIV, maximum, tariff T4'},
    {shortName: 92, obisCode: '8.8.0', isStatic: true, isGeneral: true, description: 'reactive power QIV, total'},
    {shortName: 93, obisCode: '8.8.1', isStatic: true, isGeneral: true, description: 'reactive power QIV, tariff T1'},
    {shortName: 94, obisCode: '8.8.2', isStatic: true, isGeneral: true, description: 'reactive power QIV, tariff T2'},
    {shortName: 95, obisCode: '8.8.3', isStatic: true, isGeneral: true, description: 'reactive power QIV, tariff T3'},
    {shortName: 96, obisCode: '8.8.4', isStatic: true, isGeneral: true, description: 'reactive power QIV, tariff T4'},
    {shortName: 97, obisCode: '9.5.0', isStatic: true, isGeneral: true, description: 'apparent power+ (QI+QIV), average'},
    {shortName: 98, obisCode: '9.8.0', isStatic: true, isGeneral: true, description: 'apparent power+ (QI+QIV), total'},
    {shortName: 99, obisCode: '10.5.0', isStatic: true, isGeneral: true, description: 'apparent power- (QII+QIII), average'},
    {shortName: 100, obisCode: '10.8.0', isStatic: true, isGeneral: true, description: 'apparent power- (QII+QIII), total'},
    {shortName: 101, obisCode: '15.4.0', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), current avg. 1'},
    {shortName: 102, obisCode: '15.5.0', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), average'},
    {shortName: 103, obisCode: '15.6.0', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), maximum, total'},
    {shortName: 104, obisCode: '15.6.1', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), maximum, tariff T1'},
    {shortName: 105, obisCode: '15.6.2', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), maximum, tariff T2'},
    {shortName: 106, obisCode: '15.6.3', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), maximum, tariff T3'},
    {shortName: 107, obisCode: '15.6.4', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), maximum, tariff T4'},
    {shortName: 108, obisCode: '15.8.0', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), total'},
    {shortName: 109, obisCode: '15.8.1', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), tariff T1'},
    {shortName: 110, obisCode: '15.8.2', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), tariff T2'},
    {shortName: 111, obisCode: '15.8.3', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), tariff T3'},
    {shortName: 112, obisCode: '15.8.4', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), tariff T4'},
    {shortName: 113, obisCode: '16.4.0', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), current avg. 1'},
    {shortName: 114, obisCode: '16.5.0', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), average'},
    {shortName: 115, obisCode: '16.6.0', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), maximum, total'},
    {shortName: 116, obisCode: '16.6.1', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), maximum, tariff T1'},
    {shortName: 117, obisCode: '16.6.2', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), maximum, tariff T2'},
    {shortName: 118, obisCode: '16.6.3', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), maximum, tariff T3'},
    {shortName: 119, obisCode: '16.6.4', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), maximum, tariff T4'},
    {shortName: 120, obisCode: '16.8.0', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), total'},
    {shortName: 121, obisCode: '16.8.1', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), tariff T1'},
    {shortName: 122, obisCode: '16.8.2', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), tariff T2'},
    {shortName: 123, obisCode: '16.8.3', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), tariff T3'},
    {shortName: 124, obisCode: '16.8.4', isStatic: true, isGeneral: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), tariff T4'},
    {shortName: 125, obisCode: '11.5.0', isStatic: true, isGeneral: true, description: 'current phase L1 average'},
    {shortName: 126, obisCode: '31.5.0', isStatic: true, isGeneral: true, description: 'current phase L1 average'},
    {shortName: 127, obisCode: '51.5.0', isStatic: true, isGeneral: true, description: 'current phase L2 average'},
    {shortName: 128, obisCode: '71.5.0', isStatic: true, isGeneral: true, description: 'current phase L3 average'},
    {shortName: 129, obisCode: '91.5.0', isStatic: true, isGeneral: true, description: 'current neutral average'},
    {shortName: 130, obisCode: '12.5.0', isStatic: true, isGeneral: true, description: 'voltage average'},
    {shortName: 131, obisCode: '32.5.0', isStatic: true, isGeneral: true, description: 'voltage phase L1 average'},
    {shortName: 132, obisCode: '52.5.0', isStatic: true, isGeneral: true, description: 'voltage phase L2 average'},
    {shortName: 133, obisCode: '72.5.0', isStatic: true, isGeneral: true, description: 'voltage phase L3 average'},

    // static, instantaneous
    {shortName: 134, obisCode: '1.7.0', isStatic: true, isInstantaneous: true, description: 'active power+ (QI+QIV)'},
    {shortName: 135, obisCode: '21.7.0', isStatic: true, isInstantaneous: true, description: 'active power+ (QI+QIV), L1'},
    {shortName: 136, obisCode: '41.7.0', isStatic: true, isInstantaneous: true, description: 'active power+ (QI+QIV), L2'},
    {shortName: 137, obisCode: '61.7.0', isStatic: true, isInstantaneous: true, description: 'active power+ (QI+QIV), L3'},
    {shortName: 138, obisCode: '2.7.0', isStatic: true, isInstantaneous: true, description: 'active power- (QII+QIII)'},
    {shortName: 139, obisCode: '22.7.0', isStatic: true, isInstantaneous: true, description: 'active power- (QII+QIII), L1'},
    {shortName: 140, obisCode: '42.7.0', isStatic: true, isInstantaneous: true, description: 'active power- (QII+QIII), L2'},
    {shortName: 141, obisCode: '62.7.0', isStatic: true, isInstantaneous: true, description: 'active power- (QII+QIII), L3'},
    {shortName: 142, obisCode: '3.7.0', isStatic: true, isInstantaneous: true, description: 'reactive power+ (QI+QII)'},
    {shortName: 143, obisCode: '23.7.0', isStatic: true, isInstantaneous: true, description: 'reactive power+ (QI+QII), L1'},
    {shortName: 144, obisCode: '43.7.0', isStatic: true, isInstantaneous: true, description: 'reactive power+ (QI+QII), L2'},
    {shortName: 145, obisCode: '63.7.0', isStatic: true, isInstantaneous: true, description: 'reactive power+ (QI+QII), L3'},
    {shortName: 146, obisCode: '4.7.0', isStatic: true, isInstantaneous: true, description: 'reactive power- (QIII+QIV)'},
    {shortName: 147, obisCode: '24.7.0', isStatic: true, isInstantaneous: true, description: 'reactive power- (QIII+QIV), L1'},
    {shortName: 148, obisCode: '44.7.0', isStatic: true, isInstantaneous: true, description: 'reactive power- (QIII+QIV), L2'},
    {shortName: 149, obisCode: '64.7.0', isStatic: true, isInstantaneous: true, description: 'reactive power- (QIII+QIV), L3'},
    {shortName: 150, obisCode: '11.7.0', isStatic: true, isInstantaneous: true, description: 'current'},
    {shortName: 151, obisCode: '31.7.0', isStatic: true, isInstantaneous: true, description: 'current, L1'},
    {shortName: 152, obisCode: '51.7.0', isStatic: true, isInstantaneous: true, description: 'current, L2'},
    {shortName: 153, obisCode: '71.7.0', isStatic: true, isInstantaneous: true, description: 'current, L3'},
    {shortName: 154, obisCode: '12.7.0', isStatic: true, isInstantaneous: true, description: 'voltage'},
    {shortName: 155, obisCode: '32.7.0', isStatic: true, isInstantaneous: true, description: 'voltage, L1'},
    {shortName: 156, obisCode: '52.7.0', isStatic: true, isInstantaneous: true, description: 'voltage, L2'},
    {shortName: 157, obisCode: '72.7.0', isStatic: true, isInstantaneous: true, description: 'voltage, L3'},
    {shortName: 158, obisCode: '13.7.0', isStatic: true, isInstantaneous: true, description: 'sum Li Power factor'},
    {shortName: 159, obisCode: '33.7.0', isStatic: true, isInstantaneous: true, description: 'power factor, L1'},
    {shortName: 160, obisCode: '53.7.0', isStatic: true, isInstantaneous: true, description: 'power factor, L2'},
    {shortName: 161, obisCode: '73.7.0', isStatic: true, isInstantaneous: true, description: 'power factor, L3'},
    {shortName: 162, obisCode: '14.7.0', isStatic: true, isInstantaneous: true, description: 'sum supply frequency'},
    {shortName: 163, obisCode: '34.7.0', isStatic: true, isInstantaneous: true, description: 'supply frequency, L1'},
    {shortName: 164, obisCode: '54.7.0', isStatic: true, isInstantaneous: true, description: 'supply frequency, L2'},
    {shortName: 165, obisCode: '74.7.0', isStatic: true, isInstantaneous: true, description: 'supply frequency, L3'},
    {shortName: 166, obisCode: '15.7.0', isStatic: true, isInstantaneous: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII))'},
    {shortName: 167, obisCode: '35.7.0', isStatic: true, isInstantaneous: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), L1'},
    {shortName: 168, obisCode: '55.7.0', isStatic: true, isInstantaneous: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), L2'},
    {shortName: 169, obisCode: '75.7.0', isStatic: true, isInstantaneous: true, description: 'active power (abs(QI+QIV)+(abs(QII+QIII)), L3'},
    {shortName: 170, obisCode: '16.7.0', isStatic: true, isInstantaneous: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII))'},
    {shortName: 171, obisCode: '36.7.0', isStatic: true, isInstantaneous: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), L1'},
    {shortName: 172, obisCode: '56.7.0', isStatic: true, isInstantaneous: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), L2'},
    {shortName: 173, obisCode: '76.7.0', isStatic: true, isInstantaneous: true, description: 'active power (abs(QI+QIV)-abs(QII+QIII)), L3'},
    {shortName: 174, obisCode: '17.7.0', isStatic: true, isInstantaneous: true, description: 'active power QI'},
    {shortName: 175, obisCode: '37.7.0', isStatic: true, isInstantaneous: true, description: 'active power QI, L1'},
    {shortName: 176, obisCode: '57.7.0', isStatic: true, isInstantaneous: true, description: 'active power QI, L2'},
    {shortName: 177, obisCode: '77.7.0', isStatic: true, isInstantaneous: true, description: 'active power QI, L3'},
    {shortName: 178, obisCode: '18.7.0', isStatic: true, isInstantaneous: true, description: 'active power QII'},
    {shortName: 179, obisCode: '38.7.0', isStatic: true, isInstantaneous: true, description: 'active power QII, L1'},
    {shortName: 180, obisCode: '58.7.0', isStatic: true, isInstantaneous: true, description: 'active power QII, L2'},
    {shortName: 181, obisCode: '78.7.0', isStatic: true, isInstantaneous: true, description: 'active power QII, L3'},
    {shortName: 182, obisCode: '19.7.0', isStatic: true, isInstantaneous: true, description: 'active power QIII'},
    {shortName: 183, obisCode: '39.7.0', isStatic: true, isInstantaneous: true, description: 'active power QIII, L1'},
    {shortName: 184, obisCode: '59.7.0', isStatic: true, isInstantaneous: true, description: 'active power QIII, L2'},
    {shortName: 185, obisCode: '79.7.0', isStatic: true, isInstantaneous: true, description: 'active power QIII, L3'},
    {shortName: 186, obisCode: '20.7.0', isStatic: true, isInstantaneous: true, description: 'active power QIV'},
    {shortName: 187, obisCode: '40.7.0', isStatic: true, isInstantaneous: true, description: 'active power QIV, L1'},
    {shortName: 188, obisCode: '60.7.0', isStatic: true, isInstantaneous: true, description: 'active power QIV, L2'},
    {shortName: 189, obisCode: '80.7.0', isStatic: true, isInstantaneous: true, description: 'active power QIV, L3'},
    {shortName: 190, obisCode: '81.7.1', isStatic: true, isInstantaneous: true, description: 'angle of U(L2) - U(L1)'},
    {shortName: 191, obisCode: '81.7.2', isStatic: true, isInstantaneous: true, description: 'angle of U(L3) - U(L2)'},
    {shortName: 192, obisCode: '91.7.0', isStatic: true, isInstantaneous: true, description: 'L0 current (neutral)'},

    // static, abstract
    {shortName: 193, obisCode: '0.0.0', isStatic: true, isAbstract: true, description: 'device ID'},
    {shortName: 194, obisCode: '0.2.0', isStatic: true, isAbstract: true, description: 'active firmware identifier'},
    {shortName: 195, obisCode: '0.2.1', isStatic: true, isAbstract: true, description: 'active firmware version'},
    {shortName: 196, obisCode: '0.2.8', isStatic: true, isAbstract: true, description: 'active firmware signature'},
    {shortName: 197, obisCode: '0.9.1', isStatic: true, isAbstract: true, description: 'local time'},
    {shortName: 198, obisCode: '0.9.2', isStatic: true, isAbstract: true, description: 'local date'},
    {shortName: 199, obisCode: 'F.F.0*255', isStatic: true, isAbstract: true, description: 'fatal error meter status'},

    // reassignable
    {shortName: 210, obisCode: 'C.5.0', isStatic: false, description: 'internal operating status, global'},
    {shortName: 211, obisCode: 'C.5.1', isStatic: false, description: 'internal operating status (status word 1)'},
    {shortName: 212, obisCode: 'C.5.2', isStatic: false, description: 'internal operating status (status word 2)'},
    {shortName: 213, obisCode: 'C.5.3', isStatic: false, description: 'internal operating status (status word 3)'},
    {shortName: 214, obisCode: 'C.5.4', isStatic: false, description: 'internal operating status (status word 4)'},
    {shortName: 215, obisCode: 'C.5.5', isStatic: false, description: 'meter started status flag'},
    {shortName: 216, obisCode: 'C.7.0', isStatic: false, description: 'number of power failures'},
    {shortName: 217, obisCode: 'C.7.5', isStatic: false, description: 'number of long power failures'},
    {shortName: 218, obisCode: 'C.10.0', isStatic: false, description: 'status information missing voltage'},
    {shortName: 219, obisCode: 'C.10.1', isStatic: false, description: 'status information missing current'},
    {shortName: 220, obisCode: 'C.10.2', isStatic: false, description: 'status information current without voltage'},
    {shortName: 221, obisCode: 'C.10.3', isStatic: false, description: 'status information auxiliary power supply'},
    {shortName: 222, obisCode: 'C.20.0', isStatic: false, description: 'meter open event counter'},
    {shortName: 223, obisCode: 'C.20.1', isStatic: false, description: 'meter open event, time stamp of current event occurrence'},
    {shortName: 224, obisCode: 'C.20.5', isStatic: false, description: 'terminal cover open event counter'},
    {shortName: 225, obisCode: 'C.20.6', isStatic: false, description: 'terminal cover open event, time stamp of current event occurrence'},
    {shortName: 226, obisCode: 'C.20.10', isStatic: false, description: 'tilt event counter'},
    {shortName: 227, obisCode: 'C.20.11', isStatic: false, description: 'tilt event, time stamp of current event occurrence'},
    {shortName: 228, obisCode: 'C.20.15', isStatic: false, description: 'strong DC magnetic field event counter'},
    {shortName: 229, obisCode: 'C.20.16', isStatic: false, description: 'strong DC magnetic field event, time stamp of current event occurrence'},
    {shortName: 230, obisCode: 'C.20.20', isStatic: false, description: 'supply control switch / valve tamper event counter'},
    {shortName: 231, obisCode: 'C.20.21', isStatic: false, description: 'supply control switch / valve tamper event, time stamp of current event occurrence'},
    {shortName: 232, obisCode: 'C.20.25', isStatic: false, description: 'metrology tamper event counter'},
    {shortName: 233, obisCode: 'C.20.26', isStatic: false, description: 'metrology tamper event, time stamp of current event occurrence'},
    {shortName: 234, obisCode: 'C.20.30', isStatic: false, description: 'communication tamper event counter'},
    {shortName: 235, obisCode: 'C.20.31', isStatic: false, description: 'communication tamper event, time stamp of current event occurrence'}
];
