root:
  - changed-files:
    - any-glob-to-any-file: '*'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'
      - 'typedoc.json'

source:
  - changed-files:
    - any-glob-to-any-file: 'src/**'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**'
      - 'jest.config.json'
