/**
 * The command gives the pulse counter's full value for the previous day's billing hour.
 *
 * This command is generated by the sensor and sent within a specified period without a request from the server when configured to issue daily consumption data.
 *
 * @packageDocumentation
 *
 * @example create command instance from command body hex dump
 * ```js
 * import * as dayMc from 'jooby-codec/analog/commands/uplink/dayMc.js';
 *
 * // 4 channels at 2023.12.23 00:00:00 GMT
 * const bytes = [0x2f, 0x97, 0x55, 0x0c, 0x83, 0x01, 0x08, 0x0a];
 *
 * // decoded payload
 * const parameters = dayMc.fromBytes(bytes);
 *
 * console.log(parameters);
 * // output:
 * {
 *     startTime2000: 756604800,
 *     channelList: [
 *         {value: 12, index: 1},
 *         {value: 131, index: 3},
 *         {value: 8, index: 5},
 *         {value: 10, index: 7}
 *     ]
 * }
 * ```
 *
 * [Command format documentation](https://github.com/jooby-dev/jooby-docs/blob/main/docs/analog/commands/uplink/DayMC.md)
 */

import * as types from '../../../types.js';
import * as command from '../../utils/command.js';
import BinaryBuffer, {IBinaryBuffer} from '../../../utils/BinaryBuffer.js';
import {
    IChannelValue,
    getExtendedValue,
    setExtendedValue,
    getChannels,
    setChannels,
    getDate,
    setDate
} from '../../utils/CommandBinaryBuffer.js';
import {TTime2000, getTime2000FromDate} from '../../utils/time.js';
import {ICurrentMcResponseParameters} from './currentMc.js';
import {dayMc as commandId} from '../../constants/uplinkIds.js';
import commandNames from '../../constants/uplinkNames.js';


export interface IDayMcResponseParameters extends ICurrentMcResponseParameters {
    /**
     * Start date for requested data.
     */
    startTime2000: TTime2000;
}

export const id: types.TCommandId = commandId;
export const name: types.TCommandName = commandNames[commandId];
export const headerSize = 2;

// 2 byte for date + 2 for channels (max channels: 7)
// 4 + (7 * 4)
const COMMAND_BODY_MAX_SIZE = 32;

export const examples: command.TCommandExamples = {
    '4 channels at 2023.12.23 00:00:00 GMT': {
        id,
        name,
        headerSize,
        parameters: {
            startTime2000: 756604800,
            channelList: [
                {value: 131, index: 3},
                {value: 8, index: 5},
                {value: 10, index: 7},
                {value: 12, index: 1}
            ]
        },
        bytes: [
            0x16, 0x08,
            0x2f, 0x97, 0x55, 0x0c, 0x83, 0x01, 0x08, 0x0a
        ]
    }
};


/**
 * Decode command parameters.
 *
 * @param bytes - only body (without header)
 * @returns command payload
 */
export const fromBytes = ( bytes: types.TBytes ): IDayMcResponseParameters => {
    if ( bytes.length > COMMAND_BODY_MAX_SIZE ) {
        throw new Error(`Wrong buffer size: ${bytes.length}.`);
    }

    const buffer: IBinaryBuffer = new BinaryBuffer(bytes, false);
    const date = getDate(buffer);
    const channels = getChannels(buffer);
    const channelList = channels.map(channelIndex => ({
        value: getExtendedValue(buffer),
        index: channelIndex
    }) as IChannelValue);

    return {startTime2000: getTime2000FromDate(date), channelList};
};


/**
 * Encode command parameters.
 *
 * @param parameters - command payload
 * @returns full message (header with body)
 */
export const toBytes = ( parameters: IDayMcResponseParameters ): types.TBytes => {
    const buffer: IBinaryBuffer = new BinaryBuffer(COMMAND_BODY_MAX_SIZE, false);
    const {channelList, startTime2000} = parameters;

    setDate(buffer, startTime2000);
    setChannels(buffer, channelList);
    channelList.forEach(({value}) => {
        setExtendedValue(buffer, value);
    });

    return command.toBytes(id, buffer.getBytesToOffset());
};
