/**
 * This command is generated by the sensor and sent within a specified period without a request from the server when configured to issue hour consumption data.
 * The command contains the total value of the pulse counter for the specified hour and hourly difference, which is limited to 31-bit size.
 *
 * @packageDocumentation
 *
 * @example create command instance from command body hex dump
 * ```js
 * import * as hourMc from 'jooby-codec/analog/commands/uplink/hourMc.js';
 *
 * // 4 first channels at 2023.12.23 12:00:00 GMT
 * const bytes = [
 *     0x2f, 0x97, 0x2c, 0x0f, 0x83, 0x01, 0x0a, 0xc0,
 *     0x06, 0x0c, 0x26, 0x08, 0xea, 0x01, 0x0b
 * ];
 *
 * // decoded payload
 * const parameters = hourMc.fromBytes(bytes);
 *
 * console.log(parameters);
 * // output:
 * {
 *     startTime2000: 756648000,
 *     hours: 2,
 *     channelList: [
 *         {value: 131, index: 1, diff: [10]},
 *         {value: 832, index: 2, diff: [12]},
 *         {value: 38, index: 3, diff: [8]},
 *         {value: 234, index: 4, diff: [11]}
 *     ]
 * }
 * ```
 *
 * [Command format documentation](https://github.com/jooby-dev/jooby-docs/blob/main/docs/analog/commands/uplink/HourMC.md)
 */

import * as types from '../../../types.js';
import * as command from '../../utils/command.js';
import {TTime2000} from '../../utils/time.js';
import BinaryBuffer, {IBinaryBuffer} from '../../../utils/binary/BinaryBuffer.js';
import {
    IChannelHours,
    getChannelsValuesWithHourDiff,
    setChannelsValuesWithHourDiff
} from '../../utils/binary/buffer.js';
import {hourMc as commandId} from '../../constants/uplinkIds.js';
import commandNames from '../../constants/uplinkNames.js';


export interface IHourMcResponseParameters {
    channelList: Array<IChannelHours>;

    /**
     * Start date for requested data.
     */
    startTime2000: TTime2000;

    /**
     * Number of hours.
     */
    hours: types.TUint8;
}

export const id: types.TCommandId = commandId;
export const name: types.TCommandName = commandNames[commandId];
export const headerSize = 2;

// date 2 bytes, hour 1 byte, channelList - 1 byte, so max channelList = 4
// max hours diff - 7 (3 bit value)
// 4 + (4 channelList * 5 bytes of hour values) + (4 * 5 bytes of diff * 7 max hours diff)
const COMMAND_BODY_MAX_SIZE = 164;

export const examples: command.TCommandExamples = {
    '4 first channels at 2023.12.23 12:00:00 GMT': {
        id,
        name,
        headerSize,
        parameters: {
            startTime2000: 756648000,
            hours: 2,
            channelList: [
                {value: 131, diff: [10], index: 1},
                {value: 832, diff: [12], index: 2},
                {value: 38, diff: [8], index: 3},
                {value: 234, diff: [11], index: 4}
            ]
        },
        bytes: [
            0x17, 0x0f,
            0x2f, 0x97, 0x2c, 0x0f, 0x83, 0x01, 0x0a, 0xc0,
            0x06, 0x0c, 0x26, 0x08, 0xea, 0x01, 0x0b
        ]
    }
};


/**
 * Decode command parameters.
 *
 * @param bytes - only body (without header)
 * @returns command payload
 */
export const fromBytes = ( bytes: types.TBytes ): IHourMcResponseParameters => {
    if ( bytes.length > COMMAND_BODY_MAX_SIZE ) {
        throw new Error(`Wrong buffer size: ${bytes.length}.`);
    }

    const buffer: IBinaryBuffer = new BinaryBuffer(bytes, false);

    return getChannelsValuesWithHourDiff(buffer);
};


/**
 * Encode command parameters.
 *
 * @param parameters - command payload
 * @returns full message (header with body)
 */
export const toBytes = ( parameters: IHourMcResponseParameters ): types.TBytes => {
    const buffer: IBinaryBuffer = new BinaryBuffer(COMMAND_BODY_MAX_SIZE, false);
    const {startTime2000, hours, channelList} = parameters;

    setChannelsValuesWithHourDiff(buffer, hours, startTime2000, channelList);

    return command.toBytes(id, buffer.getBytesToOffset());
};
