name: npm-develop

on:
    # run only manually
    workflow_dispatch:

# allow only one concurrent run
concurrency: "npm-develop"

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-node@v4
            with:
                node-version: '18.x'
                cache: npm
                registry-url: https://registry.npmjs.org

          - run: npm ci
          - run: npm test
          - run: npm run build:js:clean

          - run: npm run publish:dev
            env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                NPM_CONFIG_PROVENANCE: true
