name: npm-develop

on:
    push:
        branches:
          - main
    # allow to run manually
    workflow_dispatch:

# allow only one concurrent run
concurrency: "npm-develop"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3

          - uses: actions/setup-node@v3
            with:
                node-version: '18.x'
                cache: npm
                registry-url: https://registry.npmjs.org

          - run: npm ci
          - run: npm run build:js:clean

          - run: npm run publish:dev
            env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
